[package]
name = "private-multisig-program"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "private_multisig"
path = "src/main.rs"
test = false

[lib]
path = "src/lib.rs"

[dependencies]
borsh = { version = "1", features = ["derive"] }
lee_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
risc0-zkvm = { version = "3.0.5", default-features = false, features = ["std"] }
serde = { version = "1", default-features = false, features = ["derive"] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
strip = "symbols"
