[package]
name = "private-multisig-cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "multisig"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bip39 = "2"
borsh = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
private-multisig-program = { path = "../programs/multisig" }
private-multisig-sdk = { path = "../sdk" }
rand = "0.8"
tokio = { version = "1", features = ["full"] }

common = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
key_protocol = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
lee = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
lee_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", features = ["host"] }
sequencer_service_rpc = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", features = ["client"] }
wallet = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
risc0-binfmt = "3.0.4"
risc0-zkos-v1compat = "2.2.2"
